from typing import Dict, List, TypedDict

class QuestionEntry(TypedDict):
    id: int
    question: str
    sql: str
    description: str

PREDEFINED_QUESTIONS: List[QuestionEntry] = [
    {
        "id": 1,
        "question": "Display all customers.",
        "sql": "SELECT * FROM Customers;",
        "description": "The management wants to view the complete list of registered customers."
    },
    {
        "id": 2,
        "question": "Display customers from Hyderabad.",
        "sql": "SELECT * FROM Customers WHERE City = 'Hyderabad';",
        "description": "Find customers located in Hyderabad for a regional marketing campaign."
    },
    {
        "id": 3,
        "question": "Display products priced above ₹500.",
        "sql": "SELECT * FROM Products WHERE Price > 500;",
        "description": "Identify premium products available on the platform."
    },
    {
        "id": 4,
        "question": "Find customers who joined after 2024.",
        "sql": "SELECT * FROM Customers WHERE JoinDate > '2024-12-31';",
        "description": "Analyze newly acquired customers."
    },
    {
        "id": 5,
        "question": "Display orders sorted by the latest order date.",
        "sql": "SELECT * FROM Orders ORDER BY OrderDate DESC;",
        "description": "Review the most recent customer orders."
    },
    {
        "id": 6,
        "question": "Display the first 20 products.",
        "sql": "SELECT * FROM Products LIMIT 20;",
        "description": "Quickly preview a limited number of products."
    },
    {
        "id": 7,
        "question": "Display unique customer cities.",
        "sql": "SELECT DISTINCT City FROM Customers;",
        "description": "Identify all cities where customers are located."
    },
    {
        "id": 8,
        "question": "Find products priced between ₹500 and ₹3,000.",
        "sql": "SELECT * FROM Products WHERE Price BETWEEN 500 AND 3000;",
        "description": "Identify products in the mid-price range for promotional offers."
    },
    {
        "id": 9,
        "question": "Find orders placed in January.",
        "sql": "SELECT * FROM Orders WHERE EXTRACT(MONTH FROM OrderDate) = 1;",
        "description": "Analyze sales performance during January."
    },
    {
        "id": 10,
        "question": "Display customers from Hyderabad or Bangalore.",
        "sql": "SELECT * FROM Customers WHERE City IN ('Hyderabad', 'Bangalore');",
        "description": "Target customers from selected cities."
    },
    {
        "id": 11,
        "question": "Find products not supplied by Supplier 5.",
        "sql": "SELECT * FROM Products WHERE SupplierID <> 5;",
        "description": "Review products supplied by other vendors."
    },
    {
        "id": 12,
        "question": "Calculate the total revenue.",
        "sql": "SELECT SUM(PaymentAmount) AS TotalRevenue FROM Payments;",
        "description": "Measure the overall sales generated by the company."
    },
    {
        "id": 13,
        "question": "Find the average product price.",
        "sql": "SELECT AVG(Price) AS AveragePrice FROM Products;",
        "description": "Analyze the average selling price of products."
    },
    {
        "id": 14,
        "question": "Find the highest order amount.",
        "sql": "SELECT MAX(PaymentAmount) AS HighestOrderAmount FROM Payments;",
        "description": "Identify the largest customer purchase."
    },
    {
        "id": 15,
        "question": "Find the lowest product price.",
        "sql": "SELECT MIN(Price) AS LowestPrice FROM Products;",
        "description": "Identify the least expensive product."
    },
    {
        "id": 16,
        "question": "Count the total number of products.",
        "sql": "SELECT COUNT(*) AS TotalProducts FROM Products;",
        "description": "Determine the size of the product inventory."
    },
    {
        "id": 17,
        "question": "Calculate revenue by category.",
        "sql": "SELECT c.CategoryName, SUM(oi.Quantity * oi.UnitPrice) AS Revenue FROM OrderItems oi JOIN Products p ON oi.ProductID = p.ProductID JOIN Categories c ON p.CategoryID = c.CategoryID GROUP BY c.CategoryName ORDER BY Revenue DESC;",
        "description": "Identify which product categories generate the highest revenue."
    },
    {
        "id": 18,
        "question": "Count orders by city.",
        "sql": "SELECT c.City, COUNT(o.OrderID) AS OrderCount FROM Orders o JOIN Customers c ON o.CustomerID = c.CustomerID GROUP BY c.City ORDER BY OrderCount DESC;",
        "description": "Compare customer order volumes across different cities."
    },
    {
        "id": 19,
        "question": "Count orders handled by each employee.",
        "sql": "SELECT e.EmployeeName, COUNT(o.OrderID) AS OrdersHandled FROM Orders o JOIN Employees e ON o.EmployeeID = e.EmployeeID GROUP BY e.EmployeeName ORDER BY OrdersHandled DESC;",
        "description": "Measure employee productivity."
    },
    {
        "id": 20,
        "question": "Count products supplied by each supplier.",
        "sql": "SELECT s.SupplierName, COUNT(p.ProductID) AS ProductCount FROM Products p JOIN Suppliers s ON p.SupplierID = s.SupplierID GROUP BY s.SupplierName ORDER BY ProductCount DESC;",
        "description": "Evaluate supplier contributions."
    },
    {
        "id": 21,
        "question": "Find cities having more than five customers.",
        "sql": "SELECT City, COUNT(CustomerID) AS CustomerCount FROM Customers GROUP BY City HAVING COUNT(CustomerID) > 5;",
        "description": "Identify major customer locations."
    },
    {
        "id": 22,
        "question": "Find employees handling more than twenty orders.",
        "sql": "SELECT e.EmployeeName, COUNT(o.OrderID) AS OrderCount FROM Orders o JOIN Employees e ON o.EmployeeID = e.EmployeeID GROUP BY e.EmployeeName HAVING COUNT(o.OrderID) > 20;",
        "description": "Recognize employees with high workloads."
    },
    {
        "id": 23,
        "question": "Find categories generating revenue above 100,000.",
        "sql": "SELECT c.CategoryName, SUM(oi.Quantity * oi.UnitPrice) AS TotalRevenue FROM OrderItems oi JOIN Products p ON oi.ProductID = p.ProductID JOIN Categories c ON p.CategoryID = c.CategoryID GROUP BY c.CategoryName HAVING SUM(oi.Quantity * oi.UnitPrice) > 100000;",
        "description": "Identify the best-performing product categories."
    },
    {
        "id": 24,
        "question": "Categorize orders based on their status.",
        "sql": "SELECT OrderID, Status, CASE WHEN Status = 'Delivered' THEN 'Completed' WHEN Status = 'Pending' THEN 'In Progress' WHEN Status = 'Cancelled' THEN 'Terminated' ELSE 'Unknown' END AS OrderCategory FROM Orders;",
        "description": "Classify orders as Delivered, Pending, or Cancelled."
    },
    {
        "id": 25,
        "question": "Categorize products based on price.",
        "sql": "SELECT ProductName, Price, CASE WHEN Price < 1000 THEN 'Budget' WHEN Price BETWEEN 1000 AND 5000 THEN 'Medium' WHEN Price BETWEEN 5001 AND 20000 THEN 'Premium' ELSE 'Luxury' END AS PriceCategory FROM Products;",
        "description": "Label products as Budget, Medium, Premium, or Luxury."
    },
    {
        "id": 26,
        "question": "Display customer names in uppercase.",
        "sql": "SELECT UPPER(CustomerName) AS UppercaseName FROM Customers;",
        "description": "Standardize customer names for reporting."
    },
    {
        "id": 27,
        "question": "Display the first three letters of customer names.",
        "sql": "SELECT SUBSTRING(CustomerName FROM 1 FOR 3) AS ShortName FROM Customers;",
        "description": "Generate customer name abbreviations."
    },
    {
        "id": 28,
        "question": "Find the length of each customer name.",
        "sql": "SELECT CustomerName, LENGTH(CustomerName) AS NameLength FROM Customers;",
        "description": "Analyze customer name lengths."
    },
    {
        "id": 29,
        "question": "Replace 'Electronics' with 'Electronic Goods'.",
        "sql": "SELECT REPLACE(CategoryName, 'Electronics', 'Electronic Goods') AS UpdatedCategory FROM Categories;",
        "description": "Improve category naming in reports."
    },
    {
        "id": 30,
        "question": "Calculate monthly sales.",
        "sql": "SELECT DATE_TRUNC('month', OrderDate) AS Month, SUM(p.PaymentAmount) AS MonthlySales FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID GROUP BY DATE_TRUNC('month', OrderDate) ORDER BY Month;",
        "description": "Track revenue generated each month."
    },
    {
        "id": 31,
        "question": "Calculate yearly sales.",
        "sql": "SELECT EXTRACT(YEAR FROM OrderDate) AS Year, SUM(p.PaymentAmount) AS YearlySales FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID GROUP BY EXTRACT(YEAR FROM OrderDate) ORDER BY Year;",
        "description": "Compare business performance across years."
    },
    {
        "id": 32,
        "question": "Display orders placed in the current month.",
        "sql": "SELECT * FROM Orders WHERE DATE_TRUNC('month', OrderDate) = DATE_TRUNC('month', CURRENT_DATE);",
        "description": "Review recent customer orders."
    },
    {
        "id": 33,
        "question": "Calculate the number of days taken for shipping.",
        "sql": "SELECT OrderID, ShipDate - OrderDate AS ShippingDays FROM Orders WHERE ShipDate IS NOT NULL;",
        "description": "Measure delivery performance."
    },
    {
        "id": 34,
        "question": "Display products with no supplier assigned.",
        "sql": "SELECT * FROM Products WHERE SupplierID IS NULL;",
        "description": "Identify incomplete product records."
    },
    {
        "id": 35,
        "question": "Replace NULL stock values with zero.",
        "sql": "SELECT ProductID, ProductName, COALESCE(Stock, 0) AS StockAmount FROM Products;",
        "description": "Improve inventory reporting."
    },
    {
        "id": 36,
        "question": "Display customers along with their orders.",
        "sql": "SELECT c.CustomerID, c.CustomerName, o.OrderID, o.OrderDate, o.Status FROM Customers c JOIN Orders o ON c.CustomerID = o.CustomerID;",
        "description": "View customer purchase history."
    },
    {
        "id": 37,
        "question": "Display orders along with product details.",
        "sql": "SELECT o.OrderID, p.ProductName, oi.Quantity, oi.UnitPrice FROM Orders o JOIN OrderItems oi ON o.OrderID = oi.OrderID JOIN Products p ON oi.ProductID = p.ProductID;",
        "description": "Show the products included in every order."
    },
    {
        "id": 38,
        "question": "Display products along with their category names.",
        "sql": "SELECT p.ProductID, p.ProductName, c.CategoryName FROM Products p JOIN Categories c ON p.CategoryID = c.CategoryID;",
        "description": "Organize products by category."
    },
    {
        "id": 39,
        "question": "Display orders along with payment details.",
        "sql": "SELECT o.OrderID, p.PaymentMethod, p.PaymentAmount, p.PaymentDate FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID;",
        "description": "Analyze payment information for each order."
    },
    {
        "id": 40,
        "question": "Display employees along with the orders they handled.",
        "sql": "SELECT e.EmployeeID, e.EmployeeName, o.OrderID, o.OrderDate FROM Employees e JOIN Orders o ON e.EmployeeID = o.EmployeeID;",
        "description": "Track employee performance."
    },
    {
        "id": 41,
        "question": "Find customers who never placed an order.",
        "sql": "SELECT c.* FROM Customers c LEFT JOIN Orders o ON c.CustomerID = o.CustomerID WHERE o.OrderID IS NULL;",
        "description": "Identify inactive customers."
    },
    {
        "id": 42,
        "question": "Find products that were never sold.",
        "sql": "SELECT p.* FROM Products p LEFT JOIN OrderItems oi ON p.ProductID = oi.ProductID WHERE oi.OrderItemID IS NULL;",
        "description": "Identify slow-moving inventory."
    },
    {
        "id": 43,
        "question": "Find suppliers who do not supply any products.",
        "sql": "SELECT s.* FROM Suppliers s LEFT JOIN Products p ON s.SupplierID = p.SupplierID WHERE p.ProductID IS NULL;",
        "description": "Identify inactive suppliers."
    },
    {
        "id": 44,
        "question": "Generate all possible employee and shipper combinations.",
        "sql": "SELECT e.EmployeeName, sh.ShipperName FROM Employees e CROSS JOIN Shippers sh;",
        "description": "Explore all potential shipping assignments."
    },
    {
        "id": 45,
        "question": "Display the employee-manager hierarchy.",
        "sql": "SELECT e.EmployeeName AS Employee, m.EmployeeName AS Manager FROM Employees e LEFT JOIN Employees m ON e.Department = m.Department AND e.EmployeeID <> m.EmployeeID;",
        "description": "Show reporting relationships within the organization."
    },
    {
        "id": 46,
        "question": "Find products priced above the average price.",
        "sql": "SELECT * FROM Products WHERE Price > (SELECT AVG(Price) FROM Products);",
        "description": "Identify premium products compared to the average market price."
    },
    {
        "id": 47,
        "question": "Find customers who spend more than the average customer.",
        "sql": "SELECT CustomerID, SUM(PaymentAmount) AS TotalSpent FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID GROUP BY CustomerID HAVING SUM(PaymentAmount) > (SELECT AVG(TotalAmount) FROM (SELECT SUM(PaymentAmount) AS TotalAmount FROM Orders o2 JOIN Payments p2 ON o2.OrderID = p2.OrderID GROUP BY CustomerID) sub);",
        "description": "Identify high-value customers."
    },
    {
        "id": 48,
        "question": "Find the most expensive product.",
        "sql": "SELECT * FROM Products WHERE Price = (SELECT MAX(Price) FROM Products);",
        "description": "Display the highest-priced product available."
    },
    {
        "id": 49,
        "question": "Find employees handling the maximum number of orders.",
        "sql": "SELECT EmployeeID, COUNT(OrderID) AS OrderCount FROM Orders GROUP BY EmployeeID HAVING COUNT(OrderID) = (SELECT MAX(OrderCount) FROM (SELECT COUNT(OrderID) AS OrderCount FROM Orders GROUP BY EmployeeID) sub);",
        "description": "Identify the busiest employee."
    },
    {
        "id": 50,
        "question": "Find customers who purchased products from the Electronics category.",
        "sql": "SELECT DISTINCT c.* FROM Customers c JOIN Orders o ON c.CustomerID = o.CustomerID JOIN OrderItems oi ON o.OrderID = oi.OrderID JOIN Products p ON oi.ProductID = p.ProductID JOIN Categories cat ON p.CategoryID = cat.CategoryID WHERE cat.CategoryName = 'Electronics';",
        "description": "Analyze customer buying patterns."
    },
    {
        "id": 51,
        "question": "Find products that have never been ordered.",
        "sql": "SELECT * FROM Products WHERE ProductID NOT IN (SELECT DISTINCT ProductID FROM OrderItems WHERE ProductID IS NOT NULL);",
        "description": "Identify products with no sales."
    },
    {
        "id": 52,
        "question": "Create a CTE to calculate monthly sales.",
        "sql": "WITH MonthlySalesCTE AS (SELECT DATE_TRUNC('month', OrderDate) AS Month, SUM(p.PaymentAmount) AS TotalSales FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID GROUP BY DATE_TRUNC('month', OrderDate)) SELECT * FROM MonthlySalesCTE ORDER BY Month;",
        "description": "Build a reusable monthly sales report."
    },
    {
        "id": 53,
        "question": "Create a CTE to identify top customers.",
        "sql": "WITH TopCustomersCTE AS (SELECT c.CustomerID, c.CustomerName, SUM(p.PaymentAmount) AS TotalSpent FROM Customers c JOIN Orders o ON c.CustomerID = o.CustomerID JOIN Payments p ON o.OrderID = p.OrderID GROUP BY c.CustomerID, c.CustomerName) SELECT * FROM TopCustomersCTE ORDER BY TotalSpent DESC LIMIT 5;",
        "description": "Simplify customer ranking analysis."
    },
    {
        "id": 54,
        "question": "Create a CTE to calculate category-wise revenue.",
        "sql": "WITH CategoryRevenueCTE AS (SELECT cat.CategoryName, SUM(oi.Quantity * oi.UnitPrice) AS TotalRevenue FROM OrderItems oi JOIN Products p ON oi.ProductID = p.ProductID JOIN Categories cat ON p.CategoryID = cat.CategoryID GROUP BY cat.CategoryName) SELECT * FROM CategoryRevenueCTE ORDER BY TotalRevenue DESC;",
        "description": "Generate reusable revenue summaries."
    },
    {
        "id": 55,
        "question": "Create a view named vw_OrderSummary.",
        "sql": "CREATE OR REPLACE VIEW vw_OrderSummary AS SELECT o.OrderID, c.CustomerName, e.EmployeeName, o.OrderDate, o.Status, COALESCE(p.PaymentAmount, 0) AS PaymentAmount FROM Orders o JOIN Customers c ON o.CustomerID = c.CustomerID JOIN Employees e ON o.EmployeeID = e.EmployeeID LEFT JOIN Payments p ON o.OrderID = p.OrderID;",
        "description": "Provide a reusable summary of customer orders."
    },
    {
        "id": 56,
        "question": "Create a view named vw_ProductSales.",
        "sql": "CREATE OR REPLACE VIEW vw_ProductSales AS SELECT p.ProductID, p.ProductName, cat.CategoryName, COALESCE(SUM(oi.Quantity), 0) AS TotalQuantitySold, COALESCE(SUM(oi.Quantity * oi.UnitPrice), 0) AS TotalRevenue FROM Products p JOIN Categories cat ON p.CategoryID = cat.CategoryID LEFT JOIN OrderItems oi ON p.ProductID = oi.ProductID GROUP BY p.ProductID, p.ProductName, cat.CategoryName;",
        "description": "Create a reusable report showing product sales."
    },
    {
        "id": 57,
        "question": "Create a view named vw_CustomerPurchase.",
        "sql": "CREATE OR REPLACE VIEW vw_CustomerPurchase AS SELECT c.CustomerID, c.CustomerName, COUNT(DISTINCT o.OrderID) AS TotalOrders, COALESCE(SUM(p.PaymentAmount), 0) AS TotalSpent FROM Customers c LEFT JOIN Orders o ON c.CustomerID = o.CustomerID LEFT JOIN Payments p ON o.OrderID = p.OrderID GROUP BY c.CustomerID, c.CustomerName;",
        "description": "Display complete customer purchase history."
    },
    {
        "id": 58,
        "question": "Combine customer lists using UNION.",
        "sql": "SELECT CustomerName, City FROM Customers WHERE City = 'Hyderabad' UNION SELECT CustomerName, City FROM Customers WHERE City = 'Bangalore';",
        "description": "Merge customer records from multiple cities without duplicates."
    },
    {
        "id": 59,
        "question": "Combine product lists using UNION ALL.",
        "sql": "SELECT ProductName, Price FROM Products WHERE Price < 1000 UNION ALL SELECT ProductName, Price FROM Products WHERE Price > 5000;",
        "description": "Merge product records while retaining duplicates."
    },
    {
        "id": 60,
        "question": "Find customers who ordered in both 2024 and 2025 using INTERSECT.",
        "sql": "SELECT CustomerID FROM Orders WHERE EXTRACT(YEAR FROM OrderDate) = 2024 INTERSECT SELECT CustomerID FROM Orders WHERE EXTRACT(YEAR FROM OrderDate) = 2025;",
        "description": "Identify repeat customers across years."
    },
    {
        "id": 61,
        "question": "Find customers who ordered only in 2025 using EXCEPT.",
        "sql": "SELECT CustomerID FROM Orders WHERE EXTRACT(YEAR FROM OrderDate) = 2025 EXCEPT SELECT CustomerID FROM Orders WHERE EXTRACT(YEAR FROM OrderDate) = 2024;",
        "description": "Identify newly active customers."
    },
    {
        "id": 62,
        "question": "Rank products based on total sales.",
        "sql": "SELECT p.ProductName, SUM(oi.Quantity * oi.UnitPrice) AS TotalSales, RANK() OVER (ORDER BY SUM(oi.Quantity * oi.UnitPrice) DESC) AS SalesRank FROM Products p JOIN OrderItems oi ON p.ProductID = oi.ProductID GROUP BY p.ProductID, p.ProductName;",
        "description": "Identify the best-selling products."
    },
    {
        "id": 63,
        "question": "Rank customers based on total spending.",
        "sql": "SELECT c.CustomerName, SUM(p.PaymentAmount) AS TotalSpent, DENSE_RANK() OVER (ORDER BY SUM(p.PaymentAmount) DESC) AS SpendingRank FROM Customers c JOIN Orders o ON c.CustomerID = o.CustomerID JOIN Payments p ON o.OrderID = p.OrderID GROUP BY c.CustomerID, c.CustomerName;",
        "description": "Identify the most valuable customers."
    },
    {
        "id": 64,
        "question": "Assign row numbers to all orders.",
        "sql": "SELECT OrderID, CustomerID, OrderDate, ROW_NUMBER() OVER (ORDER BY OrderDate) AS RowNum FROM Orders;",
        "description": "Generate sequential numbering for reporting."
    },
    {
        "id": 65,
        "question": "Calculate the running total of sales.",
        "sql": "SELECT PaymentDate, PaymentAmount, SUM(PaymentAmount) OVER (ORDER BY PaymentDate) AS RunningTotal FROM Payments;",
        "description": "Monitor cumulative sales growth over time."
    },
    {
        "id": 66,
        "question": "Display the previous order amount for each customer.",
        "sql": "SELECT CustomerID, OrderID, PaymentAmount, LAG(PaymentAmount, 1) OVER (PARTITION BY CustomerID ORDER BY PaymentDate) AS PreviousOrderAmount FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID;",
        "description": "Compare each purchase with the customer's previous purchase."
    },
    {
        "id": 67,
        "question": "Display the next order amount for each customer.",
        "sql": "SELECT CustomerID, OrderID, PaymentAmount, LEAD(PaymentAmount, 1) OVER (PARTITION BY CustomerID ORDER BY PaymentDate) AS NextOrderAmount FROM Orders o JOIN Payments p ON o.OrderID = p.OrderID;",
        "description": "Compare each purchase with the customer's next purchase."
    },
    {
        "id": 68,
        "question": "Calculate the moving average of sales.",
        "sql": "SELECT PaymentDate, PaymentAmount, AVG(PaymentAmount) OVER (ORDER BY PaymentDate ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MovingAvgSales FROM Payments;",
        "description": "Analyze short-term sales trends."
    },
    {
        "id": 69,
        "question": "Find the top three selling products in each category.",
        "sql": "WITH RankedProducts AS (SELECT cat.CategoryName, p.ProductName, SUM(oi.Quantity) AS TotalQty, DENSE_RANK() OVER (PARTITION BY cat.CategoryID ORDER BY SUM(oi.Quantity) DESC) AS Rank FROM OrderItems oi JOIN Products p ON oi.ProductID = p.ProductID JOIN Categories cat ON p.CategoryID = cat.CategoryID GROUP BY cat.CategoryID, cat.CategoryName, p.ProductID, p.ProductName) SELECT CategoryName, ProductName, TotalQty, Rank FROM RankedProducts WHERE Rank <= 3;",
        "description": "Identify the best-performing products within every category."
    },
    {
        "id": 70,
        "question": "Divide customers into four spending groups using NTILE(4).",
        "sql": "WITH CustomerSpending AS (SELECT c.CustomerID, c.CustomerName, COALESCE(SUM(p.PaymentAmount), 0) AS TotalSpent FROM Customers c LEFT JOIN Orders o ON c.CustomerID = o.CustomerID LEFT JOIN Payments p ON o.OrderID = p.OrderID GROUP BY c.CustomerID, c.CustomerName) SELECT CustomerID, CustomerName, TotalSpent, NTILE(4) OVER (ORDER BY TotalSpent DESC) AS SpendingGroup FROM CustomerSpending;",
        "description": "Divide customers into four spending groups using NTILE(4)."
    }
]

# Fast lookup dictionary mapping normalized question text -> SQL entry
QUESTION_LOOKUP: Dict[str, QuestionEntry] = {
    item["question"]: item for item in PREDEFINED_QUESTIONS
}